CREATE TABLE CUSTOMERS (
    CustomerID NUMBER PRIMARY KEY,
    Name VARCHAR2(50),
    Age NUMBER,
    Balance NUMBER(10,2),
    IsVIP VARCHAR2(5)
);

CREATE TABLE LOANS (
    LoanID NUMBER PRIMARY KEY,
    CustomerID NUMBER,
    InterestRate NUMBER(5,2),
    DueDate DATE,
    CONSTRAINT FK_CUSTOMER
        FOREIGN KEY (CustomerID)
        REFERENCES CUSTOMERS(CustomerID)
);

INSERT INTO CUSTOMERS VALUES (1, 'Rahul', 65, 15000, 'FALSE');
INSERT INTO CUSTOMERS VALUES (2, 'Priya', 35, 8000, 'FALSE');
INSERT INTO CUSTOMERS VALUES (3, 'Amit', 70, 12000, 'FALSE');

COMMIT;

SELECT * FROM CUSTOMERS;

INSERT INTO LOANS VALUES (101, 1, 8, DATE '2026-07-20');
INSERT INTO LOANS VALUES (102, 2, 10, DATE '2026-08-25');
INSERT INTO LOANS VALUES (103, 3, 9, DATE '2026-07-10');

COMMIT;

SELECT * FROM LOANS;