CREATE TABLE ACCOUNTS (
    AccountID NUMBER PRIMARY KEY,
    CustomerName VARCHAR2(50),
    AccountType VARCHAR2(20),
    Balance NUMBER(10,2)
);

INSERT INTO ACCOUNTS VALUES (101, 'Rahul', 'Savings', 15000);
INSERT INTO ACCOUNTS VALUES (102, 'Priya', 'Savings', 8000);
INSERT INTO ACCOUNTS VALUES (103, 'Amit', 'Current', 12000);
INSERT INTO ACCOUNTS VALUES (104, 'Sneha', 'Savings', 20000);

COMMIT;

SELECT * FROM ACCOUNTS;